### ISSUE TITLE
Pretrained weights not available

### ISSUE THREAD

**Issue by alexgczs** [zhaoyuzhi/PyTorch-Special-Pre-trained-Models#3]
Hi!
This work is really interesting, can you upload again the model`s weights? It seems that they are not available.

**Comment by zhaoyuzhi** [comment]
updated. please check

**Comment by alexgczs** [comment]
Thank you a lot!!!

**Comment by alexgczs** [comment]
Thank you a lot!!!

**Comment by alexgczs** [comment]
Thank you, really fast!
Congratulations for your great work.

Greetings,
Alex.
